### ISSUE TITLE
Improve (or remove?) `EventHandler`

### ISSUE THREAD

**Issue by JoshOrndorff** [PureStake/nimbus#29]
After reading the authorship info from the pre-runtime digest, the nimbus system (fka pallet-author-inherent) notifies other subscribers (probably the staking system, etc) of the author. There are two main shortcomings of the current approach:

1. It doesn't account for weight consumed by the code being notified.
1. It introduces a custom trait that is very similar to https://crates.parity.io/pallet_authorship/trait.EventHandler.html

Ideally, we could share code with Substrate for the common task of authorship, and I've made a proposal in https://github.com/paritytech/substrate/issues/10437, and if Parity likes it, that is the preferred way to go. Solution candidates would be:
1. Follow the proposal I linked.
2. Update our trait to return weight.
3. Remove the notification system entirely, and make other pallets query for the author using `FindAuthor`

**Comment by librelois** [comment]
I think we should start with solution 2 in the short term and switch to solution 1 in the medium term.

**Comment by goozang-records** [comment]
Removed in https://github.com/PureStake/nimbus/pull/72 , we basically chose (3)
