### ISSUE TITLE
update to polkadot v0.9.24

### ISSUE THREAD

**Issue by DappGuy** [PureStake/nimbus#66]
We are using nimbus in our hackathon project and we must use the latest polkadot version. is it possible to get a v0.9.24 branch or should we do it ourselves? :)

**Comment by crystalin** [comment]
At the current moment, it would be easier to provide a PR for it as the Moonbeam team is currently focus on v0.9.23 compatibility.
I don't think there is a lot of changes in v0.9.24 so it shouldn't be too complex

**Comment by DappGuy** [comment]
Understood, thanks for the fast response

**Comment by ghzlatarev** [comment]
> At the current moment, it would be easier to provide a PR for it as the Moonbeam team is currently focus on v0.9.23 compatibility.
I don't think there is a lot of changes in v0.9.24 so it shouldn't be too complex

I can do that, we also need 0.9.24. Just not sure if I should branch off main or the 0.9.23 branch @crystalin

**Comment by notlesh** [comment]
> > At the current moment, it would be easier to provide a PR for it as the Moonbeam team is currently focus on v0.9.23 compatibility.
> > I don't think there is a lot of changes in v0.9.24 so it shouldn't be too complex
> 
> I can do that, we also need 0.9.24. Just not sure if I should branch off main or the 0.9.23 branch @crystalin

We start from `main` and preferably merge back in when done, so I would suggest opening a PR when you've gotten started.

Thanks!

**Comment by notlesh** [comment]
It looks like there is a significant diff between `main` and `moonbeam-polkadot-v0.9.23` (our latest dependency update branch), so you may want to either:

* start from `main` and reference `moonbeam-polkadot-v0.9.23` changes to help you
* start from `moonbeam-polkadot-v0.9.23` and remove the irrelevant parts (esp. branch / repo changes in `Cargo.toml` files).

(CC @librelois)

**Comment by ghzlatarev** [comment]
> It looks like there is a significant diff between `main` and `moonbeam-polkadot-v0.9.23` (our latest dependency update branch), so you may want to either:
> 
> * start from `main` and reference `moonbeam-polkadot-v0.9.23` changes to help you
> * start from `moonbeam-polkadot-v0.9.23` and remove the irrelevant parts (esp. branch / repo changes in `Cargo.toml` files).
> 
> (CC @librelois)

Thanks for the pointer, here's the PR https://github.com/PureStake/nimbus/pull/68
Btw I noticed that in the `moonbeam-polkadot-v0.9.23` branch the `cumulus` dependency is using your own fork, but in main the Cumulus are using Parity repo like the other dependencies. So I wasn't sure which one to use.

**Comment by librelois** [comment]
> Btw I noticed that in the moonbeam-polkadot-v0.9.23 branch the cumulus dependency is using your own fork, but in main the Cumulus are using Parity repo like the other dependencies. So I wasn't sure which one to use.

Thank you @ghzlatarev for your help :) 

You should use the official cumulus release, we use a custom fork for specific moonbeam needs, because we need changes not merged upstream yet.
