### ISSUE TITLE
Block invalid issue

### ISSUE THREAD

**Issue by Aideepakchaudhary** [PureStake/nimbus#69]
I have integrated the nimbus in our parachain. But Getting this error: 
<img width="1486" alt="Screenshot 2022-07-15 at 1 15 14 AM" src="https://user-images.githubusercontent.com/54492415/179781774-04ef8083-46a2-4955-aa9a-1edbb05b3c5a.png">
Can anyone please help me solve this ? 
Thanks in advance !!

**Comment by JoshOrndorff** [comment]
We need more info.
1. Where is your code?
2. How many validators and collators.
3. Do all collators produce this error?
4. What command did you use to start your collators?

**Comment by Aideepakchaudhary** [comment]
Here is the code: https://github.com/PankajChaudhary5/parachain-staking/commit/fa4eabfa9e5a0b40af286c3e8110e17bae8dddfc

I'm using this command to run collators: 
./target/release/parachain-collator \
--alice \
--collator \
--force-authoring \
--chain rococo-local-parachain-2000-raw.json \
--base-path /tmp/parachain/alice \
--port 40333 \
--ws-port 8844 \
-- \
--execution wasm \
--chain <relay chain raw chain spec> \
--port 30343 \
--ws-port 9977

Thanks for fast reply!!

**Comment by JoshOrndorff** [comment]
The error message is telling you that the author who authored this block is not eligible to author. When operating normally, this should not happen.

But you have used the `--force-authoring` flag. This instructs your node to author blocks regardless of whether it is eligible. It is no surprise that you get this error when you force authoring.

**Comment by Deepakchaudharyai** [comment]
After removing  `--force-authoring` flag. Now this error is showing:
<img width="1371" alt="Screenshot 2022-07-24 at 6 00 22 PM" src="https://user-images.githubusercontent.com/74783415/180647134-e1c7def1-3ef4-4841-a021-9b6c173ebb91.png">

**Comment by JoshOrndorff** [comment]
There are no errors in that screenshot. `Skipping candidate production...` is the normal log that is expected when your node is not eligible.
