### ISSUE TITLE
How Many TPS?

### ISSUE THREAD

**Issue by octavei** [PureStake/nimbus#85]
I really like this random consensus and want to use it in my own project. But I have a question, will it affect tps? What is the specific tps?

**Comment by crystalin** [comment]
It doesn't really affect TPS.
Using it you can achieve the maximum allowed blocks by the relay.
Depending on what filtering you use, it might be impacted by the quality of the collators. For exemple if you select only 1 collator per block, and that collator is not doing a good job, then you will miss a block

**Comment by octavei** [comment]
> It doesn't really affect TPS. Using it you can achieve the maximum allowed blocks by the relay. Depending on what filtering you use, it might be impacted by the quality of the collators. For exemple if you select only 1 collator per block, and that collator is not doing a good job, then you will miss a block

Thank you for your enthusiastic explanation. I have successfully used staking here. This is an excellent consensus protocol.
